[workspace]

[workspace.package]
version = "0.1.0"
authors = ["Maxim Khitrov <mkhitrov@blackrockneuro.com>"]
edition = "2021"
rust-version = "1.66"
license = "MPL-2.0"
publish = false

[package]
name = "burble"
description = "User-mode Bluetooth LE library"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[workspace.dependencies]
num_enum = "0.5.7"
structbuf = { version = "0", path = "../structbuf-rs" }
strum = { version = "0.24.1", features = ["derive"] }

[dependencies]
aes = "0.8.2"
bitflags = "1.3.2"
burble-const = { path = "const" }
cmac = "0.7.1"
getrandom = "0.2.8"
lock_api = "0.4.9"
num_enum.workspace = true
p256 = { version = "0.12.0", features = ["arithmetic"] }
parking_lot = { version = "0.12.1", features = ["hardware-lock-elision", "send_guard"] }
rusb = "0.9.1"
smallvec = { version = "1.10.0", features = ["const_generics", "const_new", "union"] }
structbuf.workspace = true
strum.workspace = true
subtle = "2.4.1"
thiserror = "1.0.36"
tokio = { version = "1.21.2", features = ["macros", "parking_lot", "rt", "sync", "time"] }
tokio-util = "0.7.4"
tracing = "0.1.36"
zeroize = { version = "1.5.7", features = ["zeroize_derive"] }

[dev-dependencies]
anyhow = "1.0.65"
clap = { version = "4.1.3", features = ["derive"] }
matches = "0.1.9"
tracing-subscriber = "0.3.15"
