[build]
rustflags = [
    "-Wmissing_debug_implementations",
    "-Wnon_ascii_idents",
    "-Wsingle_use_lifetimes",
    # "-Wunused_crate_dependencies", # Doesn't work for dev dependencies used in examples
    "-Wunused_extern_crates",
    "-Wunused_import_braces",
    "-Wunused_lifetimes",
    "-Wunused_qualifications",
    "-Wvariant_size_differences",
    "-Wclippy::cargo",
    "-Wclippy::nursery",
    "-Aclippy::redundant_pub_crate",
    "-Wclippy::pedantic",
    "-Aclippy::enum_glob_use",
    "-Aclippy::inline_always",
    "-Aclippy::missing_errors_doc", # TODO: Remove
    "-Aclippy::missing_panics_doc", # TODO: Remove
    "-Aclippy::module_name_repetitions",
    "-Aclippy::similar_names",
    "-Aclippy::wildcard_imports",
    # "-Wclippy::restriction",
    "-Wclippy::assertions_on_result_states",
    "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::dbg_macro",
    "-Wclippy::decimal_literal_representation",
    "-Wclippy::default_union_representation",
    "-Wclippy::deref_by_slicing",
    "-Wclippy::empty_drop",
    "-Wclippy::empty_structs_with_brackets",
    "-Wclippy::exhaustive_enums",
    "-Wclippy::exit",
    "-Wclippy::fn_to_numeric_cast_any",
    "-Wclippy::format_push_string",
    "-Wclippy::get_unwrap",
    "-Wclippy::if_then_some_else_none",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::missing_enforced_import_renames",
    "-Wclippy::mixed_read_write_in_expression",
    "-Wclippy::mod_module_files",
    "-Wclippy::mutex_atomic",
    "-Wclippy::pattern_type_mismatch",
    "-Wclippy::print_stdout",
    "-Wclippy::rc_buffer",
    "-Wclippy::rc_mutex",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    # "-Wclippy::semicolon_outside_block", # Unknown???
    "-Wclippy::str_to_string",
    "-Wclippy::string_add",
    "-Wclippy::string_to_string",
    "-Wclippy::suspicious_xor_used_as_pow",
    "-Wclippy::todo",
    "-Wclippy::try_err",
    "-Wclippy::undocumented_unsafe_blocks",
    "-Wclippy::unnecessary_safety_comment",
    "-Wclippy::unnecessary_safety_doc",
    "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unneeded_field_pattern",
    "-Wclippy::unseparated_literal_suffix",
]
