[package]
name = "burble-const"
description = "Database of Bluetooth assigned numbers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
num_enum.workspace = true
paste = "1.0.11"
structbuf.workspace = true
strum.workspace = true
